/*
 * lili.c
 *
 *  Created on: Aug 3, 2019
 *      Author: oks
 */

#include "lili.h"

void SILL_main(void) {
    printf("\n----------------------\n");
    printf("LINKEDLIST Testing:\n\n");
    printf("Singular:\n");
    snode_t * head = NULL;
    int length = 0;
    int is_circular;
    head = SILL_InitLlist(1);
    printf("Initialized List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    SILL_ConvertLineToCirc(&head);
    for (int i = 2; i <= 10; i++)
        SILL_PushBwd(head, i);
    printf("Full        List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    SILL_ConvertCircToLine(&head);
    SILL_PushFwd(&head, 10);
    printf("Pushfwd     List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    (void)SILL_PopHead(&head);
    printf("Popfwd      List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    SILL_PushFwd(&head, 0);
    printf("Pushfwd     List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    (void)SILL_PopLast(head);
    printf("Poplast     List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    (void)SILL_PopIdx(&head, 8);
    printf("Popindex    List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    (void)SILL_PopVal(&head, 5);
    printf("Popvalue    List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    (void)SILL_PushIdx(&head, 4, 5);
    printf("Pushindex   List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    (void)SILL_PushIdx(&head, 7, 8);
    printf("Pushindex   List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    (void)SILL_SwapLL(&head, 1, 8);
    printf("Swap        List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    (void)SILL_SwapLL(&head, 1, 8);
    printf("Swap        List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    printf("Linear      List: ");
    SILL_PrintList(head);
    is_circular = SILL_IsCircular(head);
    printf("Circle: %d\n", is_circular);
    printf("Linear      List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    SILL_ConvertLineToCirc(&head);
    is_circular = SILL_IsCircular(head);
    printf("Circle: %d\n", is_circular);
    printf("Circular    List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    SILL_ConvertCircToLine(&head);
    is_circular = SILL_IsCircular(head);
    printf("Circle: %d\n", is_circular);
    printf("Linear      List: ");
    SILL_PrintList(head);
    length = SILL_GetLength(head);
    printf("Length: %d\n", length);
    SILL_DeleteLlist(&head);
}

void DOLL_main(void) {
    printf("\nDoubular:\n");
    dnode_t * head = NULL;
    int length = 0;
//    int is_circular;
    head = DOLL_InitLlist(1);
    printf("Initialized  List: ");
    DOLL_PrintList(head);
    length = DOLL_GetLength(head);
    printf("Length: %d\n", length);
//    DOLL_ConvertLineToCirc(&head);
    for (int i = 2; i <= 10; i++)
        DOLL_PushBwd(head, i);
    printf("Full         List: ");
    DOLL_PrintList(head);
    length = DOLL_GetLength(head);
    printf("Length: %d\n", length);
//    DOLL_ConvertCircToLine(&head);
    DOLL_PushFwd(&head, 10);
    printf("Pushfwd     List: ");
    DOLL_PrintList(head);
    length = DOLL_GetLength(head);
    printf("Length: %d\n", length);
//    (void)DOLL_PopHead(&head);
//    printf("Popfwd      List: ");
//    DOLL_PrintList(head);
//    length = DOLL_GetLength(head);
//    printf("Length: %d\n", length);
//    DOLL_PushFwd(&head, 0);
//    printf("Pushfwd     List: ");
//    DOLL_PrintList(head);
//    length = DOLL_GetLength(head);
//    printf("Length: %d\n", length);
//    (void)DOLL_PopLast(head);
//    printf("Poplast     List: ");
//    DOLL_PrintList(head);
//    length = DOLL_GetLength(head);
//    printf("Length: %d\n", length);
//    (void)DOLL_PopIdx(&head, 8);
//    printf("Popindex    List: ");
//    DOLL_PrintList(head);
//    length = DOLL_GetLength(head);
//    printf("Length: %d\n", length);
//    (void)DOLL_PopVal(&head, 5);
//    printf("Popvalue    List: ");
//    DOLL_PrintList(head);
//    length = DOLL_GetLength(head);
//    printf("Length: %d\n", length);
    (void)DOLL_PushIdx(&head, 4, 100);
    printf("Pushindex   List: ");
    DOLL_PrintList(head);
    length = DOLL_GetLength(head);
    printf("Length: %d\n", length);
//    (void)DOLL_PushIdx(&head, 7, 8);
//    printf("Pushindex   List: ");
//    DOLL_PrintList(head);
//    length = DOLL_GetLength(head);
//    printf("Length: %d\n", length);
//    (void)DOLL_SwapLL(&head, 1, 8);
//    printf("Swap        List: ");
//    DOLL_PrintList(head);
//    length = DOLL_GetLength(head);
//    printf("Length: %d\n", length);
//    (void)DOLL_SwapLL(&head, 1, 8);
//    printf("Swap        List: ");
//    DOLL_PrintList(head);
//    length = DOLL_GetLength(head);
//    printf("Length: %d\n", length);
//    printf("Linear      List: ");
//    DOLL_PrintList(head);
//    is_circular = DOLL_IsCircular(head);
//    printf("Circle: %d\n", is_circular);
//    printf("Linear      List: ");
//    DOLL_PrintList(head);
//    length = DOLL_GetLength(head);
//    printf("Length: %d\n", length);
//    DOLL_ConvertLineToCirc(&head);
//    is_circular = DOLL_IsCircular(head);
//    printf("Circle: %d\n", is_circular);
//    printf("Circular    List: ");
//    DOLL_PrintList(head);
//    length = DOLL_GetLength(head);
//    printf("Length: %d\n", length);
//    DOLL_ConvertCircToLine(&head);
//    is_circular = DOLL_IsCircular(head);
//    printf("Circle: %d\n", is_circular);
//    printf("Linear      List: ");
//    DOLL_PrintList(head);
//    length = DOLL_GetLength(head);
//    printf("Length: %d\n", length);
    DOLL_DeleteLlist(&head);
}
